/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Hospitals
         * @description 자연어 + 위치 복합 검색. q·lat/lng·sigungu 중 최소 하나 필수.
         *
         *     meta.total = 필터 후 진짜 전체 매칭 수(페이지 크기 아님).
         *     has_more = offset+limit < total.
         */
        get: operations["search_hospitals_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hospitals/{hospital_id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hospital Thumbnail
         * @description 병원 대표 이미지(홈페이지 스크린샷) 스트리밍.
         *
         *     S3 크롤 버킷이 public-access 차단이라 외부 직접노출이 안 돼 BE 가 중계한다.
         *     카카오/네이버 대표사진은 외부 CDN URL 을 thumbnail_url 에 직접 넣으므로 이 경로를
         *     안 탄다 — 이 엔드포인트는 우리가 찍어 S3 에 올린 스크린샷 전용. 없으면 404
         *     (FE HospitalThumbnail 이 onError 로 회색 플레이스홀더 폴백).
         */
        get: operations["get_hospital_thumbnail_api_hospitals__hospital_id__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hospitals/{hospital_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hospital Detail
         * @description 병원 상세 페이지 — 9개 영역 데이터 반환.
         *
         *     ① AI 통합 설명 (ai_description)
         *     ② 핵심 진료 정보 (services, excluded_services, equipment, prices)
         *     ③ 의료진 정보 (doctors)
         *     ④ 신뢰도·근거 (confidence, detailed_signals)
         *     ⑤ 기본 운영 정보 (location, operating_hours, contact)
         *     ⑥ 사용자 피드백 (feedback_stats)
         *     ⑦ 분류 변경 이력 (recent_changes)
         *     ⑧ 관련 병원 추천 (related_hospitals)
         *     ⑨ 메타 정보 (metadata)
         */
        get: operations["get_hospital_detail_api_hospitals__hospital_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Event
         * @description 검색 이벤트 1건 저장. 실패해도 UX에 영향 없어야 하므로 에러를 조용히 처리.
         */
        post: operations["record_event_api_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hospitals/{hospital_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Change History
         * @description 병원 분류 변경 이력 조회.
         */
        get: operations["get_change_history_api_hospitals__hospital_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Feedback
         * @description 1-tap 피드백 제출. 익명 + device_id 기반 중복 방지.
         */
        post: operations["submit_feedback_api_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/{hospital_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feedback Stats
         * @description 병원별 피드백 통계 조회.
         */
        get: operations["get_feedback_stats_api_feedback__hospital_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/specialties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Specialties
         * @description 시군구 내 진료과목별 분류완료 병원 수를 반환한다.
         *
         *     카테고리 검색(진료과목 브라우즈) 화면의 칩 렌더링에 사용.
         *     분류 전 병원은 집계에서 제외된다(sigungu_specialty GSI 미등록).
         */
        get: operations["list_specialties_api_specialties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description 시군구 내 계층형 카테고리 트리(L1 분야 → L2 세부 시술)를 반환한다.
         */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Analytics Event
         * @description 환경 컨텍스트 포함 이벤트 저장. 날씨 API 실패해도 이벤트는 저장됨.
         */
        post: operations["record_analytics_event_api_analytics_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description 저장된 건강 프로파일 조회.
         */
        get: operations["get_profile_api_analytics_profile_get"];
        put?: never;
        /**
         * Save Profile
         * @description 건강 프로파일 저장 (opt-in). 재호출 시 덮어씀.
         */
        post: operations["save_profile_api_analytics_profile_post"];
        /**
         * Delete Profile
         * @description 프로파일 삭제 — 삭제권(Right to Erasure) 보장.
         */
        delete: operations["delete_profile_api_analytics_profile_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Insights
         * @description 집계 인사이트 조회. refresh=true면 raw 이벤트를 재집계한다.
         */
        get: operations["get_insights_api_analytics_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weather
         * @description 현재 위치 날씨·환경 정보 조회. 지도 페이지 날씨 위젯용.
         */
        get: operations["get_weather_api_analytics_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsEventRequest */
        AnalyticsEventRequest: {
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "impression" | "click" | "select";
            /** Device Id */
            device_id: string;
            /** Hospital Id */
            hospital_id: string;
            /** Hospital Name */
            hospital_name: string;
            /** Standard Specialty */
            standard_specialty: string;
            /** Sigungu */
            sigungu: string;
            /** Query */
            query?: string | null;
            /** Position */
            position?: number | null;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /**
             * Gender Bucket
             * @default unknown
             */
            gender_bucket: string;
            /**
             * Age Bucket
             * @default unknown
             */
            age_bucket: string;
            /**
             * Bmi Bucket
             * @default unknown
             */
            bmi_bucket: string;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Hospital Id */
            hospital_id: string;
            /** Device Id */
            device_id: string;
            /** Primary Focus */
            primary_focus: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "agree" | "disagree";
            /** Review Text */
            review_text?: string | null;
            /** Age Bucket */
            age_bucket?: string | null;
            /** Gender Bucket */
            gender_bucket?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProfileRequest */
        ProfileRequest: {
            /** Device Id */
            device_id: string;
            /**
             * Gender Bucket
             * @enum {string}
             */
            gender_bucket: "male" | "female" | "other" | "unknown";
            /**
             * Age Bucket
             * @enum {string}
             */
            age_bucket: "teens" | "20s" | "30s" | "40s" | "50plus" | "unknown";
            /**
             * Bmi Bucket
             * @enum {string}
             */
            bmi_bucket: "underweight" | "normal" | "overweight" | "obese" | "unknown";
        };
        /** SearchEventRequest */
        SearchEventRequest: {
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "impression" | "click" | "select";
            /** Session Id */
            session_id: string;
            /** Hospital Id */
            hospital_id: string;
            /** Query */
            query?: string | null;
            /** Position */
            position?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_hospitals_api_search_get: {
        parameters: {
            query?: {
                /** @description 자연어 검색 쿼리 */
                q?: string | null;
                lat?: number | null;
                lng?: number | null;
                radius_km?: number;
                sido?: string | null;
                sigungu?: string | null;
                specialty?: string | null;
                /** @description 계층 둘러보기 L1(display_category). '기타' 해체된 의미 버킷(미용/모발·탈모 등) 포함 */
                category?: string | null;
                /** @description 계층 둘러보기 L2 세부 시술·증상 태그(primary_focus) */
                focus?: string | null;
                /** @description 0=전체 노출(기본). >0 일 때만 신뢰도 하한 필터 */
                min_confidence?: number;
                sort?: string;
                limit?: number;
                offset?: number;
                /** @description true=심평원 신고 기준 전문의 있는 곳만 필터(카테고리/시군구 경로 전용). 자연어 쿼리(q)가 있으면 무시 — AI 트랙 KB 경로 처리. */
                has_specialist?: boolean | null;
                /** @description 심평원 신고 기준으로 특정 진료과(예: 피부과) 전문의 1명 이상인 병원만 필터. 카테고리/시군구 경로 전용. 자연어 쿼리(q)가 있으면 무시. */
                specialist_dept?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hospital_thumbnail_api_hospitals__hospital_id__thumbnail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hospital_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hospital_detail_api_hospitals__hospital_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hospital_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_event_api_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_change_history_api_hospitals__hospital_id__history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                hospital_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feedback_stats_api_feedback__hospital_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hospital_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_specialties_api_specialties_get: {
        parameters: {
            query: {
                /** @description 시군구 이름. 예: 강남구 */
                sigungu: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query: {
                /** @description 시군구 이름. 예: 강남구 */
                sigungu: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_analytics_event_api_analytics_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyticsEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_analytics_profile_get: {
        parameters: {
            query: {
                device_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_profile_api_analytics_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_analytics_profile_delete: {
        parameters: {
            query: {
                device_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_insights_api_analytics_insights_get: {
        parameters: {
            query?: {
                refresh?: boolean;
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weather_api_analytics_weather_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
